<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class CitySeeder extends Seeder
{
    public function run(): void
    {
        $userId = DB::table('users')->value('id');

        // Get first 195 countries (same order as CountrySeeder assumption)
        $countryIds = DB::table('countries')
            ->orderBy('id')
            ->limit(195)
            ->pluck('id');


        if (DB::table('countries')->count() !== 195) {
            // drop all country raws
            DB::table('countries')->truncate();

            $this->call(CountrySeeder::class);
        }

        /**
         * CityValue aligned with CountrySeeder order.
         */
        $cityValue = [
            "Kabul",
            "Tirana",
            "Algiers",
            "Andorra la Vella",
            "Luanda",
            "Saint John's",
            "Buenos Aires",
            "Yerevan",
            "Canberra",
            "Vienna",
            "Baku",
            "Nassau",
            "Manama",
            "Dhaka",
            "Bridgetown",
            "Minsk",
            "Brussels",
            "Belmopan",
            "Porto-Novo",
            "Thimphu",
            "Sucre",
            "Sarajevo",
            "Gaborone",
            "Brasília",
            "Bandar Seri Begawan",
            "Sofia",
            "Ouagadougou",
            "Gitega",
            "Phnom Penh",
            "Yaoundé",
            "Ottawa",
            "Praia",
            "Bangui",
            "N'Djamena",
            "Santiago",
            "Beijing",
            "Bogotá",
            "Moroni",
            "San José",
            "Zagreb",
            "Havana",
            "Nicosia",
            "Prague",
            "Kinshasa",
            "Copenhagen",
            "Djibouti",
            "Roseau",
            "Santo Domingo",
            "Dili",
            "Quito",
            "Cairo",
            "San Salvador",
            "Malabo",
            "Asmara",
            "Tallinn",
            "Mbabane",
            "Addis Ababa",
            "Palikir",
            "Suva",
            "Helsinki",
            "Paris",
            "Libreville",
            "Banjul",
            "Tbilisi",
            "Berlin",
            "Accra",
            "Athens",
            "Saint George's",
            "Guatemala City",
            "Conakry",
            "Bissau",
            "Georgetown",
            "Port-au-Prince",
            "Tegucigalpa",
            "Budapest",
            "Reykjavík",
            "New Delhi",
            "Jakarta",
            "Tehran",
            "Baghdad",
            "Dublin",
            "Jerusalem",
            "Rome",
            "Yamoussoukro",
            "Kingston",
            "Tokyo",
            "Amman",
            "Astana",
            "Nairobi",
            "South Tarawa",
            "Kuwait City",
            "Bishkek",
            "Vientiane",
            "Riga",
            "Beirut",
            "Maseru",
            "Monrovia",
            "Tripoli",
            "Vaduz",
            "Vilnius",
            "Luxembourg",
            "Antananarivo",
            "Lilongwe",
            "Kuala Lumpur",
            "Malé",
            "Bamako",
            "Valletta",
            "Majuro",
            "Nouakchott",
            "Port Louis",
            "Mexico City",
            "Chișinău",
            "Monaco",
            "Ulaanbaatar",
            "Podgorica",
            "Rabat",
            "Maputo",
            "Naypyidaw",
            "Windhoek",
            "Yaren",
            "Kathmandu",
            "Amsterdam",
            "Wellington",
            "Managua",
            "Niamey",
            "Abuja",
            "Pyongyang",
            "Skopje",
            "Oslo",
            "Muscat",
            "Islamabad",
            "Ngerulmud",
            "Ramallah",
            "Panama City",
            "Port Moresby",
            "Asunción",
            "Lima",
            "Manila",
            "Warsaw",
            "Lisbon",
            "Doha",
            "Brazzaville",
            "Bucharest",
            "Moscow",
            "Kigali",
            "Basseterre",
            "Castries",
            "Kingstown",
            "Apia",
            "San Marino",
            "São Tomé",
            "Riyadh",
            "Dakar",
            "Belgrade",
            "Victoria",
            "Freetown",
            "Singapore",
            "Bratislava",
            "Ljubljana",
            "Honiara",
            "Mogadishu",
            "Pretoria",
            "Seoul",
            "Juba",
            "Madrid",
            "Colombo",
            "Khartoum",
            "Paramaribo",
            "Stockholm",
            "Bern",
            "Damascus",
            "Dushanbe",
            "Dodoma",
            "Bangkok",
            "Lomé",
            "Nukuʻalofa",
            "Port of Spain",
            "Tunis",
            "Ankara",
            "Ashgabat",
            "Funafuti",
            "Kampala",
            "Kyiv",
            "Abu Dhabi",
            "London",
            "Los Angeles",
            "Montevideo",
            "Tashkent",
            "Port Vila",
            "Vatican City",
            "Caracas",
            "Hanoi",
            "Sana'a",
            "Lusaka",
            "Harare"
        ];


        $cities = [];


        foreach ($countryIds as $index => $countryId) {
            $cities[] = [
                "id" => (string) Str::uuid(),
                "name" => $cityValue[$index] ?? 'Unknown',
                "user_id" => $userId,
                "country_id" => $countryId,
            ];
        }


        DB::table('cities')->insert($cities);
    }
}
